##
# Defines the server's `user_version` in the .jar
# Potentially, we can have database update scripts, depending on the SQLite `user_version`
##
userVersion: 1

##
# Apparently, these do not need to be executed in topological order based on their foreign key dependencies
##
statements:
# User
- "user.sql"
# Project
- "project/project.sql"
- "project/permission.sql"
## Project Pursuits
- "project/pursuit/pursuit.sql"
- "project/pursuit/sprint.sql"
- "project/pursuit/task.sql"
### Project Pursuit Data
- "project/pursuit/attributes/pursuitTag.sql"
- "project/pursuit/task/taskWorkEntry.sql"
## Custom defined project attributes
- "project/attributes/size.sql"
- "project/attributes/tag.sql"

#- "tests.sql"