##
# Defines the server's `user_version` in the .jar
# Potentially, we can have database update scripts, depending on the SQLite `user_version`
##
userVersion: 1

##
# Some SQLite tables declare a foreign key in their 'CREATE TABLE' query, which requires the foreign key to exist while
# creating the new table. The following list defines the execution order of SQL scripts to create a fresh new SQLite
# database. Effectively, the scripts are topologically sorted based on their foreign key dependencies.
##
scripts:
# User
- "user.sql"

# Project
- "project/project.sql"
- "project/permission.sql"
## Project Pursuits
- "project/pursuit/pursuit.sql"
- "project/pursuit/sprint.sql"
- "project/pursuit/task.sql"
### Project Pursuit Data
- "project/pursuit/attributes/pursuitTag.sql"
- "project/pursuit/task/taskWorkEntry.sql"
## Custom defined project attributes
- "project/attributes/size.sql"
- "project/attributes/tags.sql"
